### PR TITLE
Fix checkbox layout

### PR DESCRIPTION
**Pull request by timkelty**
Checkbox layout was wonky (labels on new line).
Here's a fix!

### CODE REVIEW

**Comment by engram-design** [comment]
Happy to merge this - although interested in what you're seeing as wonky. Using Chrome the checkboxes are nice and tidy - I even had to put a few special rules in there to fix this because it annoyed me.

In fact, applying this makes fields wonky. See attached before/after comparison.

Would you be able to provide a screenshot?

screen shot 2015-04-28 at 11 57 50 pm

**Comment by timkelty** [comment]
Sure:
screen shot 2015-04-28 at 10 02 15 am
screen shot 2015-04-28 at 10 02 09 am

**Comment by engram-design** [comment]
@timkelty Haha - okay so thats pretty bad :)

**Comment by timkelty** [comment]
Might have been a craft version difference?

**Comment by timkelty** [comment]
Yeah if you want to re-tweak the vertical alignment of those, I'll leave that to you.

**Comment by engram-design** [comment]
Maybe! I've been running it on the last few versions (lets say roughly past 5-6 version) and worked okay. Didn't realise it was so bad, so thanks for bringing it to my attention. +1 for the pull request too :)

**Comment by timkelty** [comment]
Yep that was it. I was on an older (2.2) install. Your previous version looks fine on 2.3.
IMO, however, you should have stuff in those labels, so I still think my PR is valid.

Might just need some pixel pushing.

**Comment by engram-design** [comment]
Yep, good call, and agree.

**Pull request merged**
